# Generated by Django 5.2.5 on 2025-12-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=5),
            preserve_default=False,
        ),
    ]
