# Generated by Django 5.2.9 on 2025-12-23 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_course_price'),
    ]

    operations = [
    ]
