# Generated by Django 5.2.9 on 2025-12-23 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20251223_0536'),
        ('app', '0005_auto_20251223_0537'),
    ]

    operations = [
    ]
